name: Code Quality Checks and Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          
      - name: Verify Poetry Installation
        run: |
          echo "Poetry version: $(poetry --version)"
          poetry --version

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Check formatting
        run: make format-check
        
      - name: Run linting
        if: success() || failure()  # Run even if format-check fails
        run: make lint
      
      - name: Run tests
        if: success() || failure()  # Run even if linting fails
        run: make test