name: Code Quality Checks

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-poetry
      - name: Check formatting
        run: make format-check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-poetry
      - name: Check linting
        run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-poetry
      - name: Run tests
        run: make test